// Direct HTTP integration test of our deployed OAuth and MCP service; never browser state.
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {randomBytes,createHash} from 'node:crypto';
const origin='https://dns-pilot.cuelayer.workers.dev',credentials=JSON.parse(fs.readFileSync('.private/reviewer.json'));
const redirect=origin+'/review/oauth-test';
const registration=await fetch(origin+'/oauth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({client_name:'DNS Pilot release verification',redirect_uris:[redirect],grant_types:['authorization_code','refresh_token'],response_types:['code'],token_endpoint_auth_method:'none',scope:'dns:read dns:write offline_access'})}).then(r=>r.json());
assert.ok(registration.client_id);
const verifier=randomBytes(32).toString('base64url'),state=randomBytes(16).toString('hex');
const auth=new URL(origin+'/authorize');for(const[k,v]of Object.entries({client_id:registration.client_id,redirect_uri:redirect,response_type:'code',scope:'dns:read dns:write offline_access',state,code_challenge:createHash('sha256').update(verifier).digest('base64url'),code_challenge_method:'S256'}))auth.searchParams.set(k,v);
const consent=await fetch(auth),html=await consent.text(),cookie=consent.headers.getSetCookie().map(x=>x.split(';')[0]).join('; '),handle=html.match(/name="handle" value="([^"]+)"/)?.[1];assert.ok(handle);
const body=new URLSearchParams({handle,decision:'sandbox',username:credentials.username,password:credentials.password});for(const scope of ['dns:read','dns:write','offline_access'])body.append('scope',scope);
const approved=await fetch(origin+'/authorize',{method:'POST',redirect:'manual',headers:{Origin:origin,Cookie:cookie},body});assert.equal(approved.status,302);
const location=new URL(approved.headers.get('location'));assert.equal(location.searchParams.get('state'),state);assert.ok(location.searchParams.get('code'));
const response=await fetch(origin+'/oauth/token',{method:'POST',body:new URLSearchParams({grant_type:'authorization_code',code:location.searchParams.get('code'),client_id:registration.client_id,redirect_uri:redirect,code_verifier:verifier})});const tokens=await response.json();assert.ok(tokens.access_token);
const rpc=async(method,params={})=>{const r=await fetch(origin+'/mcp',{method:'POST',headers:{Authorization:'Bearer '+tokens.access_token,'Content-Type':'application/json',Accept:'application/json, text/event-stream'},body:JSON.stringify({jsonrpc:'2.0',id:randomBytes(8).toString('hex'),method,params})});assert.equal(r.status,200);return r.json();};
const listed=await rpc('tools/list');assert.equal(listed.result.tools.length,6);
const call=async(name,args)=>(await rpc('tools/call',{name,arguments:args})).result;
const domain=await call('dns_list_domains',{take:25,skip:0});assert.equal(domain.structuredContent.environment,'sandbox');
const zone=await call('dns_get_records',{domain:'example.com'});assert.equal(zone.structuredContent.total,5);
const p=await call('dns_plan_change',{domain:'example.com',operations:[{action:'add',record:{type:'TXT',name:'_review',value:'dns-pilot-review=Ab C',ttl:1800}}]});assert.equal(p.structuredContent.unchangedRecordCount,5);const planId=p.structuredContent.planId;
const applied=await call('dns_apply_change',{planId});assert.equal(applied.structuredContent.status,'provider_state_verified');
const reconciled=await call('dns_reconcile_change',{planId});assert.equal(reconciled.structuredContent.snapshot.total,6);
const lookup=await call('dns_lookup',{name:'example.com',type:'NS'});assert.ok(lookup.structuredContent.observations.every(x=>x.status==='answer'));
assert.equal((await call('dns_get_records',{domain:'unowned-example.org'})).isError,true);
assert.equal((await call('purchase_domain',{domain:'example.com'})).isError,true);
const mail=await call('dns_plan_change',{domain:'example.com',operations:[{action:'replace',before:{type:'MX',name:'@',exchange:'mail.example.com',preference:10,ttl:1800},after:{type:'MX',name:'@',exchange:'other.example.com',preference:10,ttl:1800}}]});assert.equal(mail.structuredContent.mailChanged,true);assert.ok(mail.structuredContent.warnings.length);
const unchanged=await call('dns_get_records',{domain:'example.com'});assert.equal(unchanged.structuredContent.items.find(x=>x.type==='MX').exchange,'mail.example.com');
const refresh=await fetch(origin+'/oauth/token',{method:'POST',body:new URLSearchParams({grant_type:'refresh_token',refresh_token:tokens.refresh_token,client_id:registration.client_id})}).then(r=>r.json());assert.ok(refresh.access_token);
const evidence={checkedAt:new Date().toISOString(),oauthPKCE:true,refresh:true,discoveredTools:6,positiveCases:5,negativeMechanisms:3,sandboxApplyVerified:true,mailPreserved:true,publicResolvers:lookup.structuredContent.observations.map(x=>({resolver:x.resolver,status:x.status})),liveNamecheap:false};
fs.writeFileSync('.private/review-verification.json',JSON.stringify(evidence,null,2));console.log(JSON.stringify(evidence,null,2));
