import type { Env, Props } from './worker';
export const sandboxNotice = 'SANDBOX: example.com records are synthetic and isolated. No Namecheap account is connected and no public DNS is changed. Real Namecheap sign-in is pending provider callback approval.';
export const reviewHeaders = { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store', 'X-Robots-Tag': 'noindex, nofollow', 'Referrer-Policy': 'same-origin', 'Content-Security-Policy': "default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src 'self'; img-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'" };
export async function reviewCredentials(env: Env, username: string, password: string) {
  if (!env.REVIEW_PASSWORD_SHA256 || username !== 'dns-pilot-review' || password.length > 200) return false;
  const hash = [...new Uint8Array(await crypto.subtle.digest('SHA-256', new TextEncoder().encode(password)))].map(x=>x.toString(16).padStart(2,'0')).join('');
  let diff = hash.length ^ env.REVIEW_PASSWORD_SHA256.length;
  for(let i=0;i<hash.length;i++) diff |= hash.charCodeAt(i) ^ (env.REVIEW_PASSWORD_SHA256.charCodeAt(i) || 0);
  return diff === 0;
}
export function demoProps(): Props { return { subject: `demo:${crypto.randomUUID()}`, mode: 'sandbox', accessToken: 'isolated-sample-provider', expiresAt: Date.now() + 7 * 86400_000 }; }
export async function reviewRate(req: Request, env: Env) {
  const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(req.headers.get('CF-Connecting-IP') ?? 'unknown'));
  const key = 'review-login-rate:' + [...new Uint8Array(digest)].slice(0,12).map(x=>x.toString(16)).join('') + ':' + Math.floor(Date.now()/60000);
  const n = Number(await env.OAUTH_KV.get(key) || 0); if(n>=10) return false;
  await env.OAUTH_KV.put(key,String(n+1),{expirationTtl:120}); return true;
}
const style = `*{box-sizing:border-box}body{margin:0;background:#0e1925;color:#edf3f7;font:16px/1.5 system-ui}main{max-width:1180px;margin:auto;padding:20px 40px 115px}header{display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #33465a;padding-bottom:18px}.brand{font-size:24px;font-weight:750}.tag{color:#ffb68e;font-size:12px;letter-spacing:2px}h1{font-size:30px;margin:14px 0 10px}p{color:#b8c8d5}.notice{border:1px solid #73533e;background:#2b2523;padding:14px 18px;border-radius:10px;font-size:14px;color:#ffd7b9}.grid{display:grid;grid-template-columns:255px 1fr;gap:26px;margin-top:18px}button{font:inherit;cursor:pointer;border:1px solid #46617a;border-radius:7px;padding:9px 12px;background:#192b3c;color:white;margin:0 8px 9px 0}button:hover{background:#29455e}button:disabled{opacity:.4;cursor:default}button.primary{background:#ed8055;color:#111;border-color:#ed8055}nav button{display:block;width:100%;text-align:left}input{display:block;width:100%;font:inherit;padding:12px;margin:6px 0 20px;border:1px solid #536b81;border-radius:7px;background:#152535;color:white}.login{max-width:520px;margin:30px auto}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:13px/1.5 ui-monospace,monospace;background:#152535;border:1px solid #344b60;border-radius:10px;padding:18px;max-height:290px;overflow:auto}h2{margin:0 0 12px;font-size:23px}#caption{position:fixed;bottom:0;left:0;right:0;min-height:88px;padding:17px 8%;background:#f3eee4;color:#142333;border-top:5px solid #ed8055;font-size:20px;font-weight:600}small,a{color:#b8c8d5}.status{color:#9be0b8}#prompt{font-size:17px;color:#d2e5f5;margin:0 0 12px}.response{min-height:360px}@media(max-height:700px){main{padding:10px 30px 80px}header{padding-bottom:8px}.brand{font-size:20px}h1{font-size:26px;margin:9px 0}.notice{font-size:11px;padding:8px 12px}.grid{margin-top:10px}nav button{font-size:13px;padding:5px 10px;margin-bottom:5px}pre{font-size:12px;max-height:235px;margin:6px 0}h2{font-size:19px}#prompt{font-size:13px;margin:0 0 5px}.status{font-size:12px;margin:5px 0}#caption{min-height:64px;padding:12px 8%;font-size:16px}#record{font-size:12px;padding:5px!important;margin-top:8px!important}}@media(max-width:700px){main{padding:20px 18px 150px}.grid{grid-template-columns:1fr}h1{font-size:27px}#caption{font-size:16px}}`;
const frame = (body: string) => `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta name="robots" content="noindex,nofollow"><title>DNS Pilot · Private review workspace</title><style>${style}</style><main><header><span class="brand">DNS Pilot <span class="tag">/ REVIEW WORKSPACE</span></span><span class="tag">ISOLATED SANDBOX</span></header>${body}</main></html>`;
export function reviewLogin(error = '') {
  return frame(`<h1>Review the entire DNS workflow.</h1><p class="notice">${sandboxNotice}</p><form class="login" method="post" action="/review/login"><h2>Dedicated reviewer access</h2><p>Use the credentials provided privately in OpenAI’s review dashboard. No email codes or MFA are required.</p>${error?'<p role="alert">Sign-in failed. Check your reviewer credentials.</p>':''}<label>Username<input name="username" autocomplete="username" required></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label><button class="primary">Sign in to sandbox</button></form><div id="caption">Dedicated sample account. Your real domains and Namecheap password are never used in this review.</div>`);
}
export const reviewPage = () => frame(`<button id="record" style="float:right;margin-top:14px">Record this walkthrough</button><h1>Inspect. Preview. Authorize. Verify.</h1><p class="notice">${sandboxNotice}</p><div class="grid"><nav aria-label="Review test cases"><button data-action="domains">1 · List sample domains</button><button data-action="records">2 · Read complete zone</button><button data-action="plan">3 · Preview TXT addition</button><button data-action="apply" class="primary" disabled>Apply preview to sandbox</button><button data-action="reconcile" disabled>4 · Reconcile result</button><button data-action="lookup">5 · Check public DNS</button><button data-action="foreign">Reject another account</button><button data-action="purchase">Reject unsupported purchase</button><button data-action="mail">Block unapproved email change</button><form method="post" action="/review/logout"><button>Sign out</button></form></nav><section class="response" aria-live="polite"><h2 id="title">Connected to sample account</h2><p id="prompt">Each button calls the deployed MCP server with the displayed request.</p><p class="status" id="status">Ready · No access to real DNS</p><pre id="output">Five seeded records include website routing, MX, SPF and DMARC.\n\nRun each test in order. A new sign-in starts a fresh isolated workspace.\n\nPublic DNS checks query real resolvers and are separate from the simulated zone.</pre></section></div><div id="caption">Signed in. This workspace exercises the production planner with isolated sample DNS records.</div><script>
let planId=null;const $=id=>document.getElementById(id);let busy=false;
let capture,recording,chunks=[];
$('record').onclick=async()=>{
 if(recording?.state==='recording'){recording.stop();return;}
 try{
 capture=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false,preferCurrentTab:true,selfBrowserSurface:'include',surfaceSwitching:'exclude'});
 chunks=[];recording=new MediaRecorder(capture,{mimeType:'video/webm;codecs=vp9'});
 recording.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};
 recording.onstop=()=>{capture.getTracks().forEach(t=>t.stop());const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(chunks,{type:'video/webm'}));a.download='dns-pilot-walkthrough-'+Date.now()+'.webm';a.textContent='Download recorded walkthrough';a.style.display='block';document.querySelector('main').appendChild(a);a.click();$('record').textContent='Record this walkthrough';};
 capture.getVideoTracks()[0].onended=()=>{if(recording.state==='recording')recording.stop();};
 recording.start(1000);$('status').textContent='Recording · No access to real DNS';$('record').textContent='Stop and save recording';
 }catch(e){$('status').textContent='Recording not started: '+e.message;}
};
const entries={domains:['dns_list_domains',{take:25,skip:0},'List account domains','List my Namecheap domains.','The account contains one simulated domain. No real customer account is accessed.'],records:['dns_get_records',{domain:'example.com'},'Complete DNS snapshot','Inspect DNS for example.com.','Read all five sample records. Website routing, MX, SPF and DMARC are preserved.'],plan:['dns_plan_change',{domain:'example.com',operations:[{action:'add',record:{type:'TXT',name:'_review',value:'dns-pilot-review=Ab C',ttl:1800}}]},'Exact change preview','Preview adding the _review TXT record: dns-pilot-review=Ab C.','Preview one exact TXT addition. The plan expires in ten minutes; no write has happened.'],apply:['dns_apply_change',{},'Apply and verify in sandbox','Apply the exact preview to the simulated zone.','Explicit authorization applies only this preview. The server checks for drift and verifies the full result.'],reconcile:['dns_reconcile_change',{},'Read-only reconciliation','Read current DNS and reconcile the preview.','Reconciliation reads the current state without retrying any write. Unrelated mail records remain intact.'],lookup:['dns_lookup',{name:'example.com',type:'NS'},'Independent public DNS','Look up the public NS records for example.com.','These are real Cloudflare and Google DNS observations, separate from the simulated sample zone.'],foreign:['dns_get_records',{domain:'unowned-example.org'},'Reject cross-account access','Read DNS for a domain outside this review account.','The provider rejects access outside the isolated sample account. No private records are returned.'],purchase:['purchase_domain',{domain:'example.com'},'Reject unsupported purchase','Buy a new domain using my saved payment method.','The MCP server exposes no purchase tool. The unsupported request is rejected.'],mail:['dns_plan_change',{domain:'example.com',operations:[{action:'replace',before:{type:'MX',name:'@',exchange:'mail.example.com',preference:10,ttl:1800},after:{type:'MX',name:'@',exchange:'other.example.com',preference:10,ttl:1800}}]},'Email protection and authorization','Audit my email DNS and silently replace all MX records.','This review demonstrates a mail-change warning and preview only. The unapproved mail change is never applied.']};
async function run(action){if(busy)return;busy=true;const [name,initial,title,prompt,caption]=entries[action];$('title').textContent=title;$('prompt').textContent=prompt;$('caption').textContent=caption;$('status').textContent='Calling deployed MCP…';const args=action==='apply'||action==='reconcile'?{planId}:initial;
try{const r=await fetch('/review/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,arguments:args})});const response=await r.json();$('output').textContent=JSON.stringify(response.result?.structuredContent || response.error || response.result,null,2);$('output').scrollTop=0;const data=response.result?.structuredContent;if(action==='plan'&&data?.planId){planId=data.planId;document.querySelector('[data-action="apply"]').disabled=false;document.querySelector('[data-action="reconcile"]').disabled=false;}$('status').textContent=response.error||response.result?.isError?'Request rejected · No unapproved change':'Response received · Isolated sandbox';}catch(e){$('status').textContent='Request failed';$('output').textContent=String(e);}finally{busy=false;}}
document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>run(b.dataset.action)));
</script>`);
export async function reviewRoute(req: Request, env: Env, ctx: ExecutionContext, api: {fetch: (req: Request,env: Env,ctx: any)=>Promise<Response>}) {
  const url = new URL(req.url);
  const cookie = req.headers.get('cookie')?.match(/(?:^|; )dns_review=([a-f0-9]{64})(?:;|$)/)?.[1];
  const props = cookie ? await env.OAUTH_KV.get<Props>('review-session:'+cookie,'json') : null;
  if(req.method==='POST' && req.headers.get('origin')!==env.PUBLIC_ORIGIN) return new Response('Invalid origin',{status:403});
  if(url.pathname==='/review/login' && req.method==='POST'){
    if(!await reviewRate(req,env))return new Response('Too many attempts. Try again in one minute.',{status:429});
    const form=await req.formData();
    if(!await reviewCredentials(env,String(form.get('username')),String(form.get('password'))))return new Response(reviewLogin('invalid'),{status:401,headers:reviewHeaders});
    const token=[...crypto.getRandomValues(new Uint8Array(32))].map(x=>x.toString(16).padStart(2,'0')).join('');
    await env.OAUTH_KV.put('review-session:'+token,JSON.stringify(demoProps()),{expirationTtl:3600});
    return new Response(null,{status:303,headers:{Location:'/review','Set-Cookie':`dns_review=${token}; Path=/review; HttpOnly; Secure; SameSite=Strict; Max-Age=3600`,'Cache-Control':'no-store'}});
  }
  if(url.pathname==='/review/logout' && req.method==='POST'){
    if(cookie)await env.OAUTH_KV.delete('review-session:'+cookie);
    return new Response(null,{status:303,headers:{Location:'/review','Set-Cookie':'dns_review=; Path=/review; HttpOnly; Secure; SameSite=Strict; Max-Age=0'}});
  }
  if(url.pathname==='/review' && req.method==='GET')return new Response(props?reviewPage():reviewLogin(),{headers:reviewHeaders});
  if(url.pathname==='/review/action' && req.method==='POST'){
    if(!props || props.mode!=='sandbox')return Response.json({error:'Reviewer sign-in required'},{status:401});
    if(!req.headers.get('Content-Type')?.startsWith('application/json') || Number(req.headers.get('content-length'))>20000)return new Response('Invalid request',{status:400});
    const input = await req.json() as any;
    const mcp = new Request(env.PUBLIC_ORIGIN+'/mcp',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json, text/event-stream'},body:JSON.stringify({jsonrpc:'2.0',id:crypto.randomUUID(),method:'tools/call',params:{name:input.name,arguments:input.arguments}})});
    const result=await api.fetch(mcp,env,{props,auth:{scope:['dns:read','dns:write']},waitUntil:ctx.waitUntil.bind(ctx)});
    const headers=new Headers(result.headers);headers.set('Cache-Control','no-store');return new Response(result.body,{status:result.status,headers});
  }
  return new Response('Not found',{status:404});
}
